fix(): ActiveLink classes
kyeotic/raviger pull request #101
Opened 2021-08-17 10:53 UTC by n33pm

#99

2021-08-17 15:40 UTC, kyeotic requested changes

2021-08-17 15:40 UTC, kyeotic commented on src/Link.tsx
> +function absolutePath(href: string): string {
This function is odd. What behavior of the anchor tag is this trying to replicate? I'd prefer if it was done directly instead of creating an actual DOM element.

I think this function might also be unfit for purpose. `useFullPath` won't ever return the `search` or `hash`, so even if the path matches exactly this function will return a string that doesn't match.

2021-08-18 07:12 UTC, n33pm commented on src/Link.tsx
> +function absolutePath(href: string): string {
What u think about Url Object and only the pathname?

2021-08-18 15:03 UTC, kyeotic commented on src/Link.tsx
> +function absolutePath(href: string): string {
That seems much better

2021-08-19 10:33 UTC, n33pm commented on src/Link.tsx
> +function absolutePath(href: string): string {
look at https://codesandbox.io/s/crazy-fog-kymde and link "fifth"

```html
<ActiveLink href="fifth" activeClass="active" exactActiveClass="exact">
  fifth
</ActiveLink>
```

`href` without leading slash would then never be shown as `active` or `exact`.

2021-08-19 15:39 UTC, kyeotic commented on src/Link.tsx
> +function absolutePath(href: string): string {
Hmm, I hadn't given this situation enough thought yet. The behavior of links with and without the leading slash is supposed to be different; leading slashes indicate relative to the domain, no leading slash indicates relative to the current page.

I think you have the correct solution here, but this introduces new surface area that should be tested. Would you mind adding a test for the no-leading-slash matching?

2021-08-19 18:59 UTC, kyeotic approved these changes

2021-08-19 18:59 UTC, merged

2021-08-19 19:04 UTC, kyeotic commented
Nice work on this @n33pm, this has been published under `2.5.2`